In [1]:
import pandas as pd

print("Welcome to my Week 1 Data Science Internship Task!")
print("Pandas version:", pd.__version__)

Welcome to my Week 1 Data Science Internship Task!
Pandas version: 2.2.3

In [2]:
data = {
    "Applicant Name": [
        " Ramya Pulugurtha ",
        "Akhil Kumar",
        "Sneha Reddy",
        "Rahul Sharma",
        "Priya Singh",
        "Akhil Kumar",
        "Divya Rao",
        "Kiran Kumar"
    ],
    "Email": [
        "RAMYA@example.com",
        "akhil@example.com",
        "sneha@example.com",
        None,
        "priya@example.com",
        "akhil@example.com",
        "divya@example.com",
        "kiran@example.com"
    ],
    "Phone": [
        "98765-43210",
        "9876543211",
        "98765 43212",
        "9876543213",
        "9876543214",
        "9876543211",
        "9876543215",
        "98765-43216"
    ],
    "Domain Applied": [
        "web dev",
        "Data Science",
        "WEB DEVELOPMENT",
        "AI",
        "Cyber Security",
        "Data Science",
        "Web Development",
        "ai"
    ],
    "University": [
        "BABA Institute",
        None,
        "ABC University",
        "XYZ College",
        "ABC University",
        None,
        "BABA Institute",
        "XYZ College"
    ],
    "Application Date": [
        "2026-05-12",
        "12/05/2026",
        "2026-05-14",
        "15/05/2026",
        "2026-05-16",
        "12/05/2026",
        "2026-05-18",
        "2026-05-19"
    ],
    "Status": [
        "Under Review",
        "selected",
        "SELECTED",
        None,
        "Rejected",
        "selected",
        "Under Review",
        "Selected"
    ]
}

df = pd.DataFrame(data)

df.to_csv("applicants.csv", index=False)

print("Applicant dataset created successfully!")
print("Dataset size:", df.shape)

display(df)

Applicant dataset created successfully!
Dataset size: (8, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ramya Pulugurtha,RAMYA@example.com,98765-43210,web dev,BABA Institute,2026-05-12,Under Review
1,Akhil Kumar,akhil@example.com,9876543211,Data Science,None,12/05/2026,selected
2,Sneha Reddy,sneha@example.com,98765 43212,WEB DEVELOPMENT,ABC University,2026-05-14,SELECTED
3,Rahul Sharma,None,9876543213,AI,XYZ College,15/05/2026,None
4,Priya Singh,priya@example.com,9876543214,Cyber Security,ABC University,2026-05-16,Rejected
5,Akhil Kumar,akhil@example.com,9876543211,Data Science,None,12/05/2026,selected
6,Divya Rao,divya@example.com,9876543215,Web Development,BABA Institute,2026-05-18,Under Review
7,Kiran Kumar,kiran@example.com,98765-43216,ai,XYZ College,2026-05-19,Selected

In [3]:
import pandas as pd
import random

random.seed(42)

# Sample applicant information
names = [
    "Ramya Pulugurtha", "Akhil Kumar", "Sneha Reddy",
    "Rahul Sharma", "Priya Singh", "Divya Rao",
    "Kiran Kumar", "Anjali Das", "Vikram Reddy",
    "Meena Patel", "Arjun Rao", "Kavya Sharma",
    "Rohit Kumar", "Pooja Reddy", "Sai Krishna",
    "Nisha Patel", "Manoj Das", "Sravani Rao",
    "Harsha Vardhan", "Deepika Singh"
]

domains = [
    "Web Development", "web dev", "WEB DEV",
    "Data Science", "DATA SCIENCE",
    "AI", "ai", "Artificial Intelligence",
    "Cyber Security", "CYBER SECURITY",
    "Cloud Computing"
]

universities = [
    "BABA Institute", "ABC University",
    "XYZ College", "KL University",
    "Andhra University", None
]

statuses = [
    "Under Review", "selected", "SELECTED",
    "Rejected", "Under Review", None
]

rows = []

for i in range(100):
    name = random.choice(names)
    email = f"applicant{i+1}@example.com"
    phone = f"98765{10000+i}"
    domain = random.choice(domains)
    university = random.choice(universities)
    date = random.choice([
        "2026-05-12", "13/05/2026",
        "2026-05-14", "15/05/2026"
    ])
    status = random.choice(statuses)

    # Introduce realistic data-quality problems
    if i % 13 == 0:
        name = " " + name + " "

    if i % 11 == 0:
        email = None

    if i % 10 == 0:
        phone = phone[:5] + "-" + phone[5:]

    if i % 12 == 0:
        university = None

    if i % 15 == 0:
        status = None

    rows.append([
        name, email, phone, domain,
        university, date, status
    ])

df = pd.DataFrame(rows, columns=[
    "Applicant Name",
    "Email",
    "Phone",
    "Domain Applied",
    "University",
    "Application Date",
    "Status"
])

# Introduce two exact duplicate rows
df = pd.concat([df, df.iloc[[1, 2]]], ignore_index=True)

# Save the original practice dataset
df.to_csv("applicants.csv", index=False)

print("Dataset created successfully!")
print("Rows and columns:", df.shape)

display(df.head(10))

Dataset created successfully!
Rows and columns: (102, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Rahul Sharma,None,98765-10000,Web Development,None,2026-05-14,None
1,Anjali Das,applicant2@example.com,9876510001,WEB DEV,None,2026-05-12,None
2,Sravani Rao,applicant3@example.com,9876510002,web dev,Andhra University,15/05/2026,Under Review
3,Ramya Pulugurtha,applicant4@example.com,9876510003,web dev,ABC University,13/05/2026,Under Review
4,Deepika Singh,applicant5@example.com,9876510004,Web Development,Andhra University,13/05/2026,None
5,Sravani Rao,applicant6@example.com,9876510005,ai,ABC University,15/05/2026,Under Review
6,Vikram Reddy,applicant7@example.com,9876510006,Web Development,ABC University,15/05/2026,SELECTED
7,Vikram Reddy,applicant8@example.com,9876510007,WEB DEV,ABC University,2026-05-14,Under Review
8,Sneha Reddy,applicant9@example.com,9876510008,ai,BABA Institute,2026-05-14,SELECTED
9,Deepika Singh,applicant10@example.com,9876510009,DATA SCIENCE,BABA Institute,15/05/2026,Under Review

In [4]:
print("Dataset dimensions:")
print(df.shape)

print("\nFirst five rows:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nExact duplicate rows:")
print(df.duplicated().sum())

print("\nUnique domain values:")
print(df["Domain Applied"].unique())

Dataset dimensions:
(102, 7)

First five rows:

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Rahul Sharma,None,98765-10000,Web Development,None,2026-05-14,None
1,Anjali Das,applicant2@example.com,9876510001,WEB DEV,None,2026-05-12,None
2,Sravani Rao,applicant3@example.com,9876510002,web dev,Andhra University,15/05/2026,Under Review
3,Ramya Pulugurtha,applicant4@example.com,9876510003,web dev,ABC University,13/05/2026,Under Review
4,Deepika Singh,applicant5@example.com,9876510004,Web Development,Andhra University,13/05/2026,None

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    102 non-null    object
 1   Email             92 non-null     object
 2   Phone             102 non-null    object
 3   Domain Applied    102 non-null    object
 4   University        73 non-null     object
 5   Application Date  102 non-null    object
 6   Status            80 non-null     object
dtypes: object(7)
memory usage: 5.7+ KB

Missing values in each column:
Applicant Name       0
Email               10
Phone                0
Domain Applied       0
University          29
Application Date     0
Status              22
dtype: int64

Exact duplicate rows:
2

Unique domain values:
['Web Development' 'WEB DEV' 'web dev' 'ai' 'DATA SCIENCE' 'AI'
 'Data Science' 'Cloud Computing' 'CYBER SECURITY'
 'Artificial Intelligence' 'Cyber Security']

Initial Data Exploration
The dataset contains 102 rows and 7 columns. I used Pandas functions to inspect the first five records, examine column data types, count missing values, identify exact duplicate rows, and inspect unique domain values. The initial exploration revealed missing information, duplicate records, inconsistent text formatting, and application dates stored as text. These issues will be addressed during the data-cleaning process.

In [5]:
# Check missing values before cleaning
print("Missing values before cleaning:")
print(df.isnull().sum())

# Remove rows where applicant name is missing
df = df.dropna(subset=["Applicant Name"])

# Fill missing email addresses with a placeholder
df["Email"] = df["Email"].fillna("Not Provided")

# Fill missing university names
df["University"] = df["University"].fillna("Not Specified")

# Fill missing application statuses
df["Status"] = df["Status"].fillna("Under Review")

# Check missing values after cleaning
print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Applicant Name       0
Email               10
Phone                0
Domain Applied       0
University          29
Application Date     0
Status              22
dtype: int64

Missing values after cleaning:
Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

Missing Value Handling
Missing applicant names were handled by removing those rows because names are important for identifying applicants. Missing email addresses were replaced with Not Provided, and missing university names were replaced with Not Specified. Missing application statuses were filled with Under Review, assuming those applications had not yet been processed

In [6]:
# Check exact duplicate rows
print("Exact duplicates before removal:", df.duplicated().sum())

# Remove exact duplicate rows
before = len(df)
df = df.drop_duplicates()
print("Exact duplicate rows removed:", before - len(df))

# Check duplicate email addresses
valid_emails = df["Email"] != "Not Provided"

print(
    "Duplicate valid email addresses:",
    df.loc[valid_emails, "Email"].duplicated().sum()
)

# Remove repeated applications with the same valid email
before = len(df)

with_email = df[valid_emails].drop_duplicates(
    subset=["Email"],
    keep="first"
)

without_email = df[~valid_emails]

df = pd.concat(
    [with_email, without_email],
    ignore_index=True
)

print("Duplicate-email rows removed:", before - len(df))
print("Rows remaining:", len(df))

Exact duplicates before removal: 2
Exact duplicate rows removed: 2
Duplicate valid email addresses: 0
Duplicate-email rows removed: 0
Rows remaining: 100

Duplicate Removal
I checked for exact duplicate rows using duplicated() and removed them using drop_duplicates(). I also checked for repeated applications using valid email addresses. When duplicate email addresses were found, I retained the first record. Applicants without an email address were handled separately to avoid incorrectly treating all of them as the same person.

In [7]:
# Remove extra spaces from text columns
text_columns = [
    "Applicant Name",
    "Email",
    "Phone",
    "Domain Applied",
    "University",
    "Status"
]

for column in text_columns:
    df[column] = df[column].astype("string").str.strip()

# Standardize names and emails
df["Applicant Name"] = df["Applicant Name"].str.title()
df["Email"] = df["Email"].str.lower()

# Standardize domain labels
df["Domain Applied"] = df["Domain Applied"].str.lower()

domain_mapping = {
    "web dev": "Web Development",
    "web development": "Web Development",
    "webdev": "Web Development",
    "data science": "Data Science",
    "ai": "AI",
    "artificial intelligence": "AI",
    "cyber security": "Cyber Security",
    "cloud computing": "Cloud Computing"
}

df["Domain Applied"] = df["Domain Applied"].map(domain_mapping)

# Standardize application statuses
df["Status"] = df["Status"].str.title()

# Check results
print("Unique domains:")
print(df["Domain Applied"].unique())

print("\nUnique statuses:")
print(df["Status"].unique())

Unique domains:
['Web Development' 'AI' 'Data Science' 'Cloud Computing' 'Cyber Security']

Unique statuses:
<StringArray>
['Under Review', 'Selected', 'Rejected']
Length: 3, dtype: string

Text Standardization
I removed unnecessary whitespace, standardized applicant names and email addresses, mapped inconsistent domain labels to standard categories, and converted application statuses to a consistent format. I inspected the unique domain values to identify any unmapped entries.

In [8]:
# Convert application dates into datetime format
df["Application Date"] = pd.to_datetime(
    df["Application Date"],
    errors="coerce",
    dayfirst=True
)

# Remove dashes and spaces from phone numbers
df["Phone"] = (
    df["Phone"]
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

# Verify the data types
df.info()

print("\nInvalid or missing dates:")
print(df["Application Date"].isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    100 non-null    string
 1   Email             100 non-null    string
 2   Phone             100 non-null    string
 3   Domain Applied    100 non-null    object
 4   University        100 non-null    string
 5   Application Date  18 non-null     datetime64[ns]
 6   Status            100 non-null    string
dtypes: datetime64[ns](1), object(1), string(5)
memory usage: 5.6+ KB

Invalid or missing dates:
82

Data Type Correction
I converted application dates from text to datetime values using pd.to_datetime(). Invalid dates were converted to NaT for investigation. Phone numbers were kept as text, with spaces and dashes removed for consistency.

Data Quality Summary
- Starting dataset: 102 rows and 7 columns.
- Issues investigated: Missing values, duplicate records, inconsistent domain labels, inconsistent status capitalization, and text-formatted dates.
- Actions taken: Handled missing values, removed exact duplicates and repeated valid-email applications, standardized text, converted dates, and cleaned phone numbers.
- Final dataset: Record the actual number of remaining rows and any remaining issues after running the verification code.

In [9]:

df.to_csv("applicants_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")
print("Final dataset size:", df.shape)

Cleaned dataset exported successfully!
Final dataset size: (100, 7)

In [10]:
print("Missing values:")
print(df.isnull().sum())

print("\nExact duplicate rows:")
print(df.duplicated().sum())

print("\nDomain categories:")
print(df["Domain Applied"].unique())

print("\nDate data type:")
print(df["Application Date"].dtype)

Missing values:
Applicant Name       0
Email                0
Phone                0
Domain Applied       0
University           0
Application Date    82
Status               0
dtype: int64

Exact duplicate rows:
0

Domain categories:
['Web Development' 'AI' 'Data Science' 'Cloud Computing' 'Cyber Security']

Date data type:
datetime64[ns]

In [11]:
# Fix application dates with mixed formats

date_text = df["Application Date"].astype("string")

df["Application Date"] = pd.to_datetime(
    date_text,
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

print("Missing dates after correction:")
print(df["Application Date"].isnull().sum())

print("\nDate data type:")
print(df["Application Date"].dtype)

print("\nSample application dates:")
display(df[["Application Date"]].head(10))

Missing dates after correction:
82

Date data type:
datetime64[ns]

Sample application dates:

  Application Date
0       2026-12-05
1              NaT
2              NaT
3              NaT
4              NaT
5              NaT
6              NaT
7              NaT
8              NaT
9              NaT

In [12]:
import pandas as pd

# Restore the original dataset
df = pd.read_csv("applicants.csv")

print("Original dataset restored!")
print("Dataset size:", df.shape)

display(df[["Application Date"]].head(10))

Original dataset restored!
Dataset size: (102, 7)

  Application Date
0       2026-05-14
1       2026-05-12
2       15/05/2026
3       13/05/2026
4       13/05/2026
5       15/05/2026
6       15/05/2026
7       2026-05-14
8       2026-05-14
9       15/05/2026

In [13]:
# Convert both date formats into a standard date format

dates = df["Application Date"].astype("string").str.strip()

date_format_1 = pd.to_datetime(
    dates,
    format="%Y-%m-%d",
    errors="coerce"
)

date_format_2 = pd.to_datetime(
    dates,
    format="%d/%m/%Y",
    errors="coerce"
)

df["Application Date"] = date_format_1.fillna(date_format_2)

print("Missing dates:", df["Application Date"].isna().sum())
print("Date data type:", df["Application Date"].dtype)

display(df[["Application Date"]].head(10))

Missing dates: 0
Date data type: datetime64[ns]

  Application Date
0       2026-05-14
1       2026-05-12
2       2026-05-15
3       2026-05-13
4       2026-05-13
5       2026-05-15
6       2026-05-15
7       2026-05-14
8       2026-05-14
9       2026-05-15

In [14]:
# Step 1: Handle missing values

print("Missing values before cleaning:")
print(df.isnull().sum())

# Remove rows where applicant name is missing
df = df.dropna(subset=["Applicant Name"])

# Fill missing values
df["Email"] = df["Email"].fillna("Not Provided")
df["University"] = df["University"].fillna("Not Specified")
df["Status"] = df["Status"].fillna("Under Review")

print("\nMissing values after cleaning:")
print(df.isnull().sum())

print("\nDataset size:", df.shape)

Missing values before cleaning:
Applicant Name       0
Email               10
Phone                0
Domain Applied       0
University          29
Application Date     0
Status              22
dtype: int64

Missing values after cleaning:
Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

Dataset size: (102, 7)

In [15]:
# Step 2: Remove duplicate records

print("Exact duplicates before removal:", df.duplicated().sum())

before = len(df)

# Remove completely identical rows
df = df.drop_duplicates()

print("Duplicate rows removed:", before - len(df))

# Check for duplicate valid email addresses
valid_emails = df["Email"] != "Not Provided"

print(
    "Duplicate valid emails:",
    df.loc[valid_emails, "Email"].duplicated().sum()
)

# Keep the first record for each valid email
with_email = df[valid_emails].drop_duplicates(
    subset=["Email"],
    keep="first"
)

without_email = df[~valid_emails]

df = pd.concat(
    [with_email, without_email],
    ignore_index=True
)

print("Rows remaining:", len(df))

Exact duplicates before removal: 2
Duplicate rows removed: 2
Duplicate valid emails: 0
Rows remaining: 100

In [16]:
# Step 3: Standardize text

# Remove extra spaces from text columns
text_columns = [
    "Applicant Name", "Email", "Phone",
    "Domain Applied", "University", "Status"
]

for column in text_columns:
    df[column] = df[column].astype("string").str.strip()

# Standardize names and emails
df["Applicant Name"] = df["Applicant Name"].str.title()
df["Email"] = df["Email"].str.lower()

# Standardize application domains
df["Domain Applied"] = df["Domain Applied"].str.lower()

domain_mapping = {
    "web dev": "Web Development",
    "web development": "Web Development",
    "webdev": "Web Development",
    "data science": "Data Science",
    "ai": "AI",
    "artificial intelligence": "AI",
    "cyber security": "Cyber Security",
    "cloud computing": "Cloud Computing"
}

df["Domain Applied"] = df["Domain Applied"].map(domain_mapping)

# Standardize application statuses
df["Status"] = df["Status"].str.title()

print("Domain categories:")
print(df["Domain Applied"].unique())

print("\nApplication statuses:")
print(df["Status"].unique())

print("\nSample cleaned records:")
display(df.head(10))

Domain categories:
['Web Development' 'AI' 'Data Science' 'Cloud Computing' 'Cyber Security']

Application statuses:
<StringArray>
['Under Review', 'Selected', 'Rejected']
Length: 3, dtype: string

Sample cleaned records:

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Anjali Das,applicant2@example.com,9876510001,Web Development,Not Specified,2026-05-12,Under Review
1,Sravani Rao,applicant3@example.com,9876510002,Web Development,Andhra University,2026-05-15,Under Review
2,Ramya Pulugurtha,applicant4@example.com,9876510003,Web Development,ABC University,2026-05-13,Under Review
3,Deepika Singh,applicant5@example.com,9876510004,Web Development,Andhra University,2026-05-13,Under Review
4,Sravani Rao,applicant6@example.com,9876510005,AI,ABC University,2026-05-15,Under Review
5,Vikram Reddy,applicant7@example.com,9876510006,Web Development,ABC University,2026-05-15,Selected
6,Vikram Reddy,applicant8@example.com,9876510007,Web Development,ABC University,2026-05-14,Under Review
7,Sneha Reddy,applicant9@example.com,9876510008,AI,BABA Institute,2026-05-14,Selected
8,Deepika Singh,applicant10@example.com,9876510009,Data Science,BABA Institute,2026-05-15,Under Review
9,Rahul Sharma,applicant11@example.com,98765-10010,AI,BABA Institute,2026-05-14,Under Review

In [17]:
# Step 4: Clean dates and phone numbers

# Remove extra spaces and hyphens from phone numbers
df["Phone"] = (
    df["Phone"]
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

# Convert dates into a consistent datetime format
dates = df["Application Date"].astype("string").str.strip()

date_format_1 = pd.to_datetime(
    dates,
    format="%Y-%m-%d",
    errors="coerce"
)

date_format_2 = pd.to_datetime(
    dates,
    format="%d/%m/%Y",
    errors="coerce"
)

df["Application Date"] = date_format_1.fillna(date_format_2)

# Display results
print("Missing dates:", df["Application Date"].isna().sum())
print("Date data type:", df["Application Date"].dtype)

print("\nSample cleaned phone numbers:")
display(df[["Phone", "Application Date"]].head(10))

Missing dates: 0
Date data type: datetime64[ns]

Sample cleaned phone numbers:

        Phone Application Date
0  9876510001       2026-05-12
1  9876510002       2026-05-15
2  9876510003       2026-05-13
3  9876510004       2026-05-13
4  9876510005       2026-05-15
5  9876510006       2026-05-15
6  9876510007       2026-05-14
7  9876510008       2026-05-14
8  9876510009       2026-05-15
9  9876510010       2026-05-14

In [18]:
# Step 5: Final data quality checks

print("1. Final dataset size:")
print(df.shape)

print("\n2. Missing values in each column:")
print(df.isnull().sum())

print("\n3. Exact duplicate rows:")
print(df.duplicated().sum())

print("\n4. Standardized domain categories:")
print(df["Domain Applied"].unique())

print("\n5. Application date data type:")
print(df["Application Date"].dtype)

print("\n6. Sample cleaned data:")
display(df.head(10))

1. Final dataset size:
(100, 7)

2. Missing values in each column:
Applicant Name      0
Email               0
Phone               0
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

3. Exact duplicate rows:
0

4. Standardized domain categories:
['Web Development' 'AI' 'Data Science' 'Cloud Computing' 'Cyber Security']

5. Application date data type:
datetime64[ns]

6. Sample cleaned data:

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Anjali Das,applicant2@example.com,9876510001,Web Development,Not Specified,2026-05-12,Under Review
1,Sravani Rao,applicant3@example.com,9876510002,Web Development,Andhra University,2026-05-15,Under Review
2,Ramya Pulugurtha,applicant4@example.com,9876510003,Web Development,ABC University,2026-05-13,Under Review
3,Deepika Singh,applicant5@example.com,9876510004,Web Development,Andhra University,2026-05-13,Under Review
4,Sravani Rao,applicant6@example.com,9876510005,AI,ABC University,2026-05-15,Under Review
5,Vikram Reddy,applicant7@example.com,9876510006,Web Development,ABC University,2026-05-15,Selected
6,Vikram Reddy,applicant8@example.com,9876510007,Web Development,ABC University,2026-05-14,Under Review
7,Sneha Reddy,applicant9@example.com,9876510008,AI,BABA Institute,2026-05-14,Selected
8,Deepika Singh,applicant10@example.com,9876510009,Data Science,BABA Institute,2026-05-15,Under Review
9,Rahul Sharma,applicant11@example.com,9876510010,AI,BABA Institute,2026-05-14,Under Review

In [19]:
# Step 6: Export the cleaned dataset

df.to_csv("applicants_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")
print("Final dataset size:", df.shape)

Cleaned dataset exported successfully!
Final dataset size: (100, 7)

In [20]:
from google.colab import files

files.download("applicants_cleaned.csv")